### ISSUE TITLE
DSi Flasher version

### ISSUE THREAD

**Issue by anuserlol** [d3m3vilurr/ak2i_ntrcardhax_flasher#8]
I know that the DSi version doesn't have a restore flash option,but why?
Also, it's posible to use the NDS version on a DSi?

**Comment by Valeri0p** [comment]
Restore flash needs a memory to save the flash backup.
Since this versions can't (for now) save on SD card, the only medium is the nds ram, but since it's erased when you shutdown, you need another device to keep turned on when you install sighax,and since you can do card swap only on Ds lite/fay, these are the only devices viable for that.

**Comment by d3m3vilurr** [comment]
Sadly, DSi mode can't swap cartridge. It means, if I add restore feature, you cannot use cartridge for the ntrboot exploit. So restore is useless on dsi/3ds
